Repository sgdevcamp2025/c_sharp, pull requests merged in 2025-02, with the labels that each got.

#95 fetch Instance 및 fetch 메서드 코드 구현
  src/frontend/.prettierrc
  src/frontend/apps/web/src/shared/apis/.keep
  src/frontend/apps/web/src/shared/services/apis/fetch-instance.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch-method.api.ts
  src/frontend/apps/web/src/shared/services/apis/index.ts
  src/frontend/apps/web/src/shared/services/index.ts
  src/frontend/apps/web/src/shared/services/models/error/authorization-errors.ts
  src/frontend/apps/web/src/shared/services/models/error/index.ts
  src/frontend/apps/web/src/shared/services/models/error/workspace-errors.ts
  src/frontend/apps/web/src/shared/services/models/index.ts
  src/frontend/apps/web/src/shared/services/models/types/fetch-types.d.ts
  src/frontend/apps/web/src/shared/services/models/types/index.ts
  src/frontend/packages/ui/package.json
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 🖥️ FE, 상

#94 인증서버 내 액세스토큰 재발급 api 구현
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/dto/UserInfoResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/dto/UserLoginRequest.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/KakaoSocialService.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/TokenService.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/response/ErrorCode.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserController.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserControllerDocs.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/Platform.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/User.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/AccessTokenGetSuccess.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/repository/UserRepository.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/repository/UserRepositoryCustom.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
Labels: ✨ Feature, 🎮 BE, 상

#99 채팅서버 초기셋팅 및 채팅 mvp api 구현
  src/backend/chat_server/.gitattributes
  src/backend/chat_server/.gitignore
  src/backend/chat_server/build.gradle
  src/backend/chat_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/chat_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/chat_server/gradlew
  src/backend/chat_server/gradlew.bat
  src/backend/chat_server/settings.gradle
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/ChatServerApplication.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/BaseTimeEntity.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/User.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageRequest.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/UserRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/chat_server/src/test/java/com/jootalkpia/chat_server/ChatServerApplicationTests.java
Labels: ✨ Feature, 📦 Environment, 🎮 BE, ♻️ Need To Refactor, 상

#98 주식리스트 테이블 레이아웃 구현
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/package.json
  src/frontend/apps/web/src/features/stock/index.tsx
  src/frontend/apps/web/src/features/stock/model/index.ts
  src/frontend/apps/web/src/features/stock/model/stock.types.ts
  src/frontend/apps/web/src/features/stock/model/stocks-table.columns.tsx
  src/frontend/apps/web/src/features/stock/ui/index.ts
  src/frontend/apps/web/src/features/stock/ui/stocks-list-table.tsx
  src/frontend/apps/web/src/features/stock/ui/stocks-list.tsx
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/DataTable/data-table.stories.tsx
  src/frontend/packages/ui/src/components/DataTable/data-table.tsx
  src/frontend/packages/ui/src/components/DataTable/index.ts
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: 🐛 BugFix, ✨ Feature, 🔧 Build, 💄 Design, 🖥️ FE, 상

#105 히스토리서버 초기셋팅
  src/backend/history_server/.gitattributes
  src/backend/history_server/.gitignore
  src/backend/history_server/build.gradle
  src/backend/history_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/history_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/history_server/gradlew
  src/backend/history_server/gradlew.bat
  src/backend/history_server/settings.gradle
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/HistoryServerApplication.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/config/MongoConfig.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/controller/HistoryController.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/BaseTimeEntity.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/ChatMessage.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/MessageType.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/ChatMessageSaveRequest.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/repository/ChatMessageRepository.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/service/HistoryCommandService.java
  src/backend/history_server/src/main/resources/application.yml
  src/backend/history_server/src/test/java/com/jootalkpia/history_server/HistoryServerApplicationTests.java
Labels: ✨ Feature, 📦 Environment, 🎮 BE

#109 파일 업로드 파트 구현
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/src/features/chat/model/file-data.type.ts
  src/frontend/apps/web/src/features/chat/model/file-upload.util.ts
  src/frontend/apps/web/src/features/chat/model/file.utils.ts
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-textarea.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-toggle-group.tsx
  src/frontend/apps/web/src/features/chat/ui/content-avatar.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preivew-list.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-item.tsx
  src/frontend/apps/web/src/features/chat/ui/file-upload-trigger.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.stories.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/index.ts
  src/frontend/packages/ui/src/components/Textarea/textarea.stories.tsx
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/packages/ui/src/components/index.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#107 페이지간 링크 연결 및 스타일링
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/src/shared/components/header/header.tsx
Labels: ✨ Feature, 🔧 Build, 💄 Design, 🖥️ FE, 중

#106 상세페이지 주식부분 레이아웃
  src/frontend/apps/web/src/features/stock/ui/stock-chart-container.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-detail-layout.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-info-container.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-info.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-logo.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#108 WebRtc mvp 구현
  .idea/.gitignore
  .idea/c_sharp.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/.DS_Store
  src/backend/.DS_Store
  src/backend/.idea/compiler.xml
  src/backend/.idea/gradle.xml
  src/backend/.idea/misc.xml
  src/backend/.idea/modules.xml
  src/backend/.idea/modules/common_module.iml
  src/backend/.idea/modules/common_module.main.iml
  src/backend/.idea/modules/common_module.test.iml
  src/backend/.idea/modules/signaling_server.main.iml
  src/backend/.idea/modules/stock_server.iml
  src/backend/.idea/modules/stock_server.main.iml
  src/backend/.idea/modules/stock_server.test.iml
  src/backend/.idea/modules/workspace_server.iml
  src/backend/.idea/modules/workspace_server.main.iml
  src/backend/.idea/modules/workspace_server.test.iml
  src/backend/signaling_server/.DS_Store
  src/backend/signaling_server/.gitattributes
  src/backend/signaling_server/.gitignore
  src/backend/signaling_server/Dockerfile
  src/backend/signaling_server/build.gradle
  src/backend/signaling_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/signaling_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/signaling_server/gradlew
  src/backend/signaling_server/gradlew.bat
  src/backend/signaling_server/settings.gradle
  src/backend/signaling_server/src/.DS_Store
  src/backend/signaling_server/src/main/.DS_Store
  src/backend/signaling_server/src/main/java/.DS_Store
  src/backend/signaling_server/src/main/java/com/.DS_Store
  src/backend/signaling_server/src/main/java/com/jootalkpia/.DS_Store
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/.DS_Store
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/SignalingServerApplication.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/config/KurentoClientConfig.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/config/WebRtcConfig.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/controller/HuddleController.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/controller/WebRtcController.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/dto/HuddleDto.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/dto/WebRtcSignalDto.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/model/Huddle.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/HuddleCacheRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/KurentoHandler.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/KurentoRoom.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/KurentoUserSession.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/HuddleService.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/KurentoManager.java
  src/backend/signaling_server/src/main/resources/application.yml
  src/backend/signaling_server/src/test/java/com/jootalkpia/signaling_server/SignalingServerApplicationTests.java
  src/backend/workspace_server/.DS_Store
  src/backend/workspace_server/src/.DS_Store
Labels: ✨ Feature, 🎮 BE, 상

#115 카프카 서버 구축 및 주식 당일일분봉 토픽 생성, producer 설정
  src/backend/stock_server/build.gradle
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/TokenResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/StockService.java
  src/backend/stock_server/src/main/resources/application.yml
Labels: ✨ Feature, 📦 Environment, 🎮 BE, ♻️ Need To Refactor, 상

#119 모달창 구현하기 & util Function vs Custom hooks에 대한 고뇌
  src/frontend/apps/web/src/features/chat/lib/file.utils.ts
  src/frontend/apps/web/src/features/chat/lib/index.ts
  src/frontend/apps/web/src/features/chat/model/file-data.type.ts
  src/frontend/apps/web/src/features/chat/model/file-upload.util.ts
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/model/use-file-managements.ts
  src/frontend/apps/web/src/features/chat/ui/chat-toggle-group.tsx
  src/frontend/apps/web/src/features/chat/ui/file-modal.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-image.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-item.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-list.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-video.tsx
  src/frontend/packages/ui/.storybook/main.ts
  src/frontend/packages/ui/src/components/Modal/modal.stories.tsx
  src/frontend/packages/ui/src/components/Modal/modal.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 상

#122 사이드바 스타일 수정 및 배치
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-header.tsx
  src/frontend/apps/web/src/shared/components/sidebar/index.ts
  src/frontend/apps/web/src/shared/components/sidebar/ui/sidebar-container.tsx
  src/frontend/packages/ui/src/components/Sidebar/sidebar.tsx
Labels: 🐛 BugFix, ✨ Feature, 🔧 Build, 💄 Design, 🖥️ FE, 상

#128 file upload시 파일을 지우고 모달창 열 때 렌더링되지않은 문제 해결
  src/frontend/apps/web/src/features/chat/model/use-file-managements.ts
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
Labels: 🐛 BugFix, 🚑 !HOTFIX, 🖥️ FE, 상

#123 인증서버 닉네임 변경 api 구현
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/config/SwaggerConfig.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtAuthenticationFilter.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/response/ErrorCode.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/security/UserAuthentication.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserController.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserControllerDocs.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/User.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/request/UpdateNicknameRequest.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/AccessTokenGetSuccess.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/LoginSuccessResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/TokenDto.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/repository/UserRepository.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
Labels: ✨ Feature, 🎮 BE, 하

#132 채팅 메시지 카프카 발행 및 수신 로직 구현
  src/backend/chat_server/build.gradle
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/MinutePriceResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaProducer.java
  src/backend/chat_server/src/main/resources/application.yml
Labels: ✨ Feature, 📦 Environment, 🎮 BE, ♻️ Need To Refactor, 상

#131 스레드 사용시 대댓글 UI 컴포넌트 구현
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/src/features/chat/index.tsx
  src/frontend/apps/web/src/features/chat/ui/avatarlist.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-header.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/apps/web/src/features/chat/ui/header.tsx
  src/frontend/apps/web/src/features/chat/ui/thread-header.tsx
  src/frontend/apps/web/src/features/chat/ui/thread-panel.tsx
  src/frontend/apps/web/src/features/chat/ui/thread-section.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 중

#129 스토리북 git action 에러 수정
  src/frontend/packages/ui/src/components/Collapsible/collapsible.stories.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle-group.stories.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle.stories.tsx
Labels: 🐛 BugFix, 🖥️ FE, 상

#138 EC2 이용 배포 카프카 주식, 채팅 서버 연결
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaProducer.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/domain/Schedule.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/StockService.java
Labels: 🚀 Deploy, 🎮 BE, 상

#134 파일서버 파일 업로드 및 저장 구현
  src/backend/file_server/.gitattributes
  src/backend/file_server/.gitignore
  src/backend/file_server/build.gradle
  src/backend/file_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/file_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/file_server/gradlew
  src/backend/file_server/gradlew.bat
  src/backend/file_server/local.env
  src/backend/file_server/settings.gradle
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/FileServerApplication.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/config/S3Config.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/controller/FileController.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/UploadFileRequestDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/UploadFileResponseDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/entity/Files.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/repository/FileRepository.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileService.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileTypeDetector.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/S3Service.java
  src/backend/file_server/src/main/resources/application.yml
  src/backend/file_server/src/test/java/com/jootalkpia/file_server/FileServerApplicationTests.java
  src/infra/.idea/.gitignore
  src/infra/.idea/infra.iml
  src/infra/.idea/misc.xml
  src/infra/.idea/modules.xml
  src/infra/.idea/vcs.xml
  src/infra/Dockerfile
  src/infra/init.sql
Labels: ✨ Feature, 🎮 BE, 상

#142 Input 마우스로 사이즈 조절 불가하도록 개선
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
Labels: 🐛 BugFix, ✨ Feature, 💄 Design, 🖥️ FE, 중

#140 사이드바 디자인 개선
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/workspace/.keep
  src/frontend/apps/web/src/features/workspace/index.tsx
  src/frontend/apps/web/src/features/workspace/ui/index.ts
  src/frontend/apps/web/src/features/workspace/ui/sidebar-container.tsx
  src/frontend/apps/web/src/shared/components/sidebar/index.ts
  src/frontend/packages/ui/src/components/Sidebar/sidebar.tsx
  src/frontend/packages/ui/src/styles/globals.css
  src/frontend/packages/ui/tailwind.config.ts
Labels: 💄 Design, 🖥️ FE, 중

#146 드롭다운 메뉴 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/DropdownMenu/dropdown-menu.stories.tsx
  src/frontend/packages/ui/src/components/DropdownMenu/dropdown-menu.tsx
  src/frontend/packages/ui/src/components/DropdownMenu/index.ts
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/packages/ui/src/styles/globals.css
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#149 주식테이블 검색바, 드롭다운 구현
  src/frontend/apps/web/src/features/stock/ui/stocks-list-table.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#152 파일서버: 파일 다운로드&프로필이미지 수정 구현
  src/backend/file_server/Dockerfile
  src/backend/file_server/local.env
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/controller/FileController.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/ChangeProfileResponseDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/entity/BaseTimeEntity.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/entity/User.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/exception/common/CustomException.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/exception/common/ErrorCode.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/exception/common/ErrorResponse.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/exception/common/GlobalExceptionHandler.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/repository/FileRepository.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/repository/UserRepository.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileService.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileTypeDetector.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/S3Service.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/utils/ValidationUtils.java
  src/backend/file_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#154 주식데이터 소켓 소켓 전달 구현
  src/backend/auth_server/Dockerfile
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#155 백엔드 cicd 설정
  .github/workflows/be-cicd.yml
  src/backend/chat_server/Dockerfile
  src/backend/history_server/Dockerfile
  src/backend/stock_server/Dockerfile
Labels: 🚀 Deploy, 📦 Environment, 🎮 BE, 상

#133 허들레이아웃 구현
  src/frontend/apps/web/app/(main)/huddle/page.tsx
  src/frontend/apps/web/src/features/video/.keep
  src/frontend/apps/web/src/features/video/index.ts
  src/frontend/apps/web/src/features/video/model/huddle-control.type.ts
  src/frontend/apps/web/src/features/video/model/huddle-controls-reducer.ts
  src/frontend/apps/web/src/features/video/model/index.ts
  src/frontend/apps/web/src/features/video/ui/huddle-container.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-control-item.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-controls-group.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-footer.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-participant-avatar.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-participant-card.tsx
  src/frontend/apps/web/src/features/video/ui/huddle-section.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle.tsx
  src/frontend/packages/ui/tailwind.config.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#158 gateway 초기셋팅
  src/backend/gateway_server/.gitattributes
  src/backend/gateway_server/.gitignore
  src/backend/gateway_server/build.gradle
  src/backend/gateway_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/gateway_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/gateway_server/gradlew
  src/backend/gateway_server/gradlew.bat
  src/backend/gateway_server/settings.gradle
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/GatewayServerApplication.java
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/GlobalFilter.java
  src/backend/gateway_server/src/main/resources/application.yml
  src/backend/gateway_server/src/test/java/com/jootalkpia/gateway_server/GatewayServerApplicationTests.java
Labels: ✨ Feature, 📦 Environment, 🎮 BE, 상

#162 주식 서버 커서 기반 페이징 기능 구현 및 예외 처리
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/ControllerAdvice.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/caller/StockCaller.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/BadRequestException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/BusinessException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/ErrorResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/InvalidObjectIdFormatException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/NoSuchMinutePriceException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/util/StockValidationUtils.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/controller/StockController.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/MinutePrice.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/CandlePriceHistoryResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/repository/MinutePriceRepository.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/StockService.java
Labels: ✨ Feature, 🎮 BE, 상

#165 인증서버 로그인api response에 profile이미지 추가
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/LoginSuccessResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/TokenDto.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/UserDto.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
Labels: ✨ Feature, 🎮 BE, 중

#166 인증서버 내 닉네임 변경 api response 수정
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserController.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserControllerDocs.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/GetAccessTokenResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/LoginResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/response/UpdateNicknameResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
Labels: ✨ Feature, 🎮 BE, 중

#168 주식 서버 IndexOutOfBoundsException 해결 및 커스텀 예외 코드 추가
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/ControllerAdvice.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/BadRequestException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/BusinessException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/ErrorResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/InvalidMinutePriceFromApiException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/InvalidObjectIdFormatException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/exception/NoSuchMinutePriceException.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/util/StockValidationUtils.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceSimpleResponse.java
  src/backend/stock_server/src/main/resources/application.yml
Labels: 🐛 BugFix, 🎮 BE, 상

#164 채팅서버 카프카 연결
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/ChatServerApplication.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/Files.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageRequest.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/ChatMessageRequest.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/CommonResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/ImageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/MessageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/TextResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/VideoResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/FileRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaProducer.java
  src/backend/chat_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, ♻️ Need To Refactor, 상

#179 헤더 로그인 버튼 추가
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/src/features/auth/index.ts
  src/frontend/apps/web/src/features/auth/ui/auth-wrapper.tsx
  src/frontend/apps/web/src/features/auth/ui/index.ts
  src/frontend/apps/web/src/features/auth/ui/login-button.tsx
  src/frontend/apps/web/src/features/auth/ui/logout-button.tsx
  src/frontend/apps/web/src/features/user/index.ts
  src/frontend/apps/web/src/features/user/ui/index.ts
  src/frontend/apps/web/src/features/user/ui/profile-nickname.tsx
  src/frontend/apps/web/src/features/user/ui/profile-picture.tsx
  src/frontend/apps/web/src/features/user/ui/profile-popover-content.tsx
  src/frontend/apps/web/src/features/user/ui/profile-popover.tsx
  src/frontend/apps/web/src/shared/components/header/header.tsx
  src/frontend/apps/web/src/shared/components/header/profile-container.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 상

#185 파일 업로드 api 구현 및 instance 수정 및 파일 업로드 관련 로직 변경 논의
  src/frontend/apps/web/src/features/chat/api/uploadFile.api.ts
  src/frontend/apps/web/src/features/chat/lib/file.utils.ts
  src/frontend/apps/web/src/features/chat/model/file-data.type.ts
  src/frontend/apps/web/src/features/chat/model/use-file-managements.ts
  src/frontend/apps/web/src/features/chat/ui/avatarlist.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-toggle-group.tsx
  src/frontend/apps/web/src/features/chat/ui/file-modal.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-item.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-list.tsx
  src/frontend/apps/web/src/shared/services/apis/fetch-instance.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch-method.api.ts
  src/frontend/apps/web/src/shared/services/lib/index.ts
  src/frontend/apps/web/src/shared/services/lib/utils.ts
  src/frontend/apps/web/src/shared/services/models/types/fetch-types.d.ts
  src/frontend/apps/web/src/shared/services/models/types/index.ts
  src/frontend/turbo.json
Labels: ✨ Feature, 🔧 Build, 🖥️ FE, 상

#183 채팅서버 채팅 produce 전 rdb 선행 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/Files.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/ReplyThread.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/Thread.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/CommonResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/ImageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/MessageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/TextResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/VideoResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/ThreadRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaProducer.java
Labels: ✨ Feature, 🎮 BE, 상

#190 Sock JS 공용로직 훅 구현 + react-query 적용하기
  src/frontend/apps/web/package.json
  src/frontend/apps/web/src/shared/hooks/.keep
  src/frontend/apps/web/src/shared/hooks/use-message.ts
  src/frontend/apps/web/src/shared/hooks/use-websocket-stomp.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 🖥️ FE, 상

#184 주식 차트 라이브러리 적용
  src/frontend/apps/web/package.json
  src/frontend/apps/web/src/features/stock/lib/index.ts
  src/frontend/apps/web/src/features/stock/lib/stock.util.ts
  src/frontend/apps/web/src/features/stock/model/index.ts
  src/frontend/apps/web/src/features/stock/model/stock-chart.mock.ts
  src/frontend/apps/web/src/features/stock/model/stock.types.ts
  src/frontend/apps/web/src/features/stock/model/use-stock-chart.ts
  src/frontend/apps/web/src/features/stock/ui/stock-chart-container.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-chart-item.tsx
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#194 채팅서버 내 채팅발행 response 변경 및 리팩토링
  .github/workflows/be-cicd.yml
  .idea/.gitignore
  .idea/c_sharp.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ChatMessageToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/CommonResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/ImageResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/TextResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/VideoResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/FileRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/util/DateTimeUtil.java
Labels: ✨ Feature, 🎮 BE, 상

#200 stock server CORS 설정
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/WebConfig.java
Labels: ✨ Feature, 🎮 BE, ♻️ Need To Refactor, 상

#195 히스토리 서버 카프카 연결
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/ChatMessage.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/Message.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/MessageType.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/ChatMessageSaveRequest.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/CommonDto.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/MessageDto.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/service/KafkaConsumer.java
Labels: ✨ Feature, 🎮 BE, 상

#203 auth서버 cors관련 설정 추가
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/config/WebConfig.java
Labels: 📦 Environment, 🎮 BE, ♻️ Need To Refactor, 상

#198 STOMP 채널 SUB/UNSUB 시 상태 관리 Redis 변경 로직 구현
  src/backend/chat_server/build.gradle
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/ChatServerApplication.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/RedisConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/StompSubscriptionInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/properties/RedisProperties.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/RedisKeys.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/state_server/build.gradle
Labels: ✨ Feature, 🎮 BE, ♻️ Need To Refactor, 상

#206 STOMP 채널 CONNECT / DISCONNECT 시 상태 관리 Redis 생성 및 삭제 로직 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompConnectInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompSubscriptionInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompValidationInterceptor.java
Labels: ✨ Feature, 🎮 BE, 상

#204 Stomp및 SockJS, React-Query를 활용한 채팅 구현
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/src/features/chat/lib/format-chat-time.util.ts
  src/frontend/apps/web/src/features/chat/lib/index.ts
  src/frontend/apps/web/src/features/chat/lib/process-message.util.ts
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/model/use-messages.ts
  src/frontend/apps/web/src/features/chat/model/use-websocket-client.ts
  src/frontend/apps/web/src/features/chat/model/websocket.type.ts
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-textarea.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-toggle-group.tsx
  src/frontend/apps/web/src/features/chat/ui/content-avatar.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/apps/web/src/features/chat/ui/thread-section.tsx
  src/frontend/apps/web/src/shared/hooks/.keep
  src/frontend/apps/web/src/shared/hooks/use-message.ts
  src/frontend/apps/web/src/shared/hooks/use-websocket-stomp.ts
  src/frontend/apps/web/src/shared/services/models/types/index.ts
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/packages/ui/src/lib/handle-shiftenter-indent.util.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 상

#201 로그인 페이지 구현
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/app/stock/[stockSlug]/page.tsx
  src/frontend/apps/web/app/stock/layout.tsx
  src/frontend/apps/web/app/stock/page.tsx
  src/frontend/apps/web/public/images/kakao_login_large_narrow.png
  src/frontend/apps/web/src/features/auth/ui/login-button.tsx
  src/frontend/apps/web/src/features/stock/ui/stocks-list-table.tsx
  src/frontend/apps/web/src/shared/components/header/header.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#209 상태 관리 Redis 내 채널 가입 유저 리스트 생성 및 추가 로직 구현
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.bin
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.bin
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/resourceHashesCache.bin
  src/backend/workspace_server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/backend/workspace_server/.gradle/buildOutputCleanup/outputFiles.bin
  src/backend/workspace_server/build.gradle
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/WorkspaceServerApplication.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/util/RedisKeys.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/util/config/RedisConfig.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/util/property/RedisProperties.java
  src/backend/workspace_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, ♻️ Need To Refactor, 상

#216 게이트웨이 서버 passport 로직 구현
  .github/workflows/be-cicd.yml
  src/backend/auth_server/build.gradle
  src/backend/auth_server/settings.gradle
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/AuthServerApplication.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtAuthenticationFilter.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtTokenProvider.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/AuthController.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserController.java
  src/backend/auth_server/src/main/resources/application.yml
  src/backend/common_module/build.gradle
  src/backend/common_module/src/main/java/com/jootalkpia/aop/JootalkpiaAuthenticationContext.java
  src/backend/common_module/src/main/java/com/jootalkpia/config/WebMvcConfig.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/HMACEncoder.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportExtractor.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportGenerator.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportValidator.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/anotation/CurrentUser.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/anotation/CurrentUserArgumentResolver.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/component/UserInfo.java
  src/backend/gateway_server/Dockerfile
  src/backend/gateway_server/build.gradle
  src/backend/gateway_server/settings.gradle
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/GlobalFilter.java
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/JwtAuthenticationFilter.java
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/PassportAuthorizationFilter.java
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/PassportRelayFilter.java
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/paths/ExcludedPaths.java
  src/backend/gateway_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#223 히스토리 서버 저장 안되는 에러 수정
  src/backend/chat_server/build.gradle
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/ChatMessage.java
Labels: 🐛 BugFix, 🎮 BE, 상

#220 FCM 메시지를 받을 유저 필터링 로직 구현
  src/backend/state_server/build.gradle
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/StateServerApplication.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/config/RedisConfig.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/config/RedisProperties.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/entity/RedisKeys.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/service/KafkaConsumer.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/service/StateService.java
  src/backend/state_server/src/main/resources/application.yml
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.bin
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.bin
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/resourceHashesCache.bin
  src/backend/workspace_server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/backend/workspace_server/.gradle/file-system.probe
Labels: ✨ Feature, 📦 Environment, 🎮 BE, 상

#232 파일 업로드 청크방식으로 구현
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/controller/FileController.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/MultipartChunk.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/UploadChunkRequestDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/UploadFileResponseDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/dto/UploadFilesResponseDto.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/exception/common/ErrorCode.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileService.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileTypeDetector.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/S3Service.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/utils/ValidationUtils.java
  src/backend/file_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#234 gateway와 각 서버 연동
  .DS_Store
  src/backend/gateway_server/build.gradle
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/filter/JwtAuthenticationFilter.java
  src/backend/gateway_server/src/main/resources/application.yml
Labels: 📦 Environment, 🎮 BE, 상

#235 버그 수정 및 채팅 자동 스크롤 및 새 메시지 알림 기능 구현을 통한 UX 개선
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/model/use-chat-autoscroll.ts
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section-content.tsx
  src/frontend/apps/web/src/features/chat/ui/header.tsx
  src/frontend/packages/ui/src/components/Toast/index.ts
Labels: 🐛 BugFix, ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 중

#228 웹소켓 연결 로직 변경과 개선 및 고민
  src/frontend/.eslintrc.js
  src/frontend/apps/web/app/layout.tsx
  src/frontend/apps/web/app/stock/[stockSlug]/page.tsx
  src/frontend/apps/web/app/stock/layout.tsx
  src/frontend/apps/web/src/features/chat/lib/format-dates.util.ts
  src/frontend/apps/web/src/features/chat/lib/index.ts
  src/frontend/apps/web/src/features/chat/lib/send-message.util.ts
  src/frontend/apps/web/src/features/chat/model/use-messages.ts
  src/frontend/apps/web/src/features/chat/model/use-websocket-client.ts
  src/frontend/apps/web/src/features/chat/model/websocket.type.ts
  src/frontend/apps/web/src/features/chat/ui/avatarlist.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-textarea.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/apps/web/src/shared/components/index.ts
  src/frontend/apps/web/src/shared/components/providers/index.ts
  src/frontend/apps/web/src/shared/components/react-query/index.ts
  src/frontend/apps/web/src/shared/index.ts
  src/frontend/apps/web/src/shared/provider/.keep
  src/frontend/apps/web/src/shared/providers/index.ts
  src/frontend/apps/web/src/shared/providers/providers.tsx
  src/frontend/apps/web/src/shared/providers/rq-provider.tsx
  src/frontend/apps/web/src/shared/providers/stomp-websocket-provider.tsx
  src/frontend/apps/web/src/shared/services/apis/index.ts
  src/frontend/apps/web/src/shared/services/apis/querykey.ts
  src/frontend/dangerfile.ts
  src/frontend/packages/eslint-config/next.js
  src/frontend/packages/eslint-config/package.json
  src/frontend/packages/typescript-config/base.json
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 🔧 Build, 🖥️ FE, ♻️ Need To Refactor, 상

#237 gateway cors 설정
  src/backend/auth_server/src/main/resources/application.yml
  src/backend/file_server/src/main/resources/application.yml
  src/backend/gateway_server/src/main/java/com/jootalkpia/gateway_server/config/GatewayCorsConfig.java
  src/backend/gateway_server/src/main/resources/application.yml
  src/backend/workspace_server/src/main/resources/application.yml
Labels: 📦 Environment, 🎮 BE, 상

#239 WS 비정상 종료에 대해 SessionDisconnectEvent를 이용한 이벤트 감지 로직 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/SessionEventListener.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompConnectInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompSubscriptionInterceptor.java
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.bin
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.bin
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.lock
  src/backend/workspace_server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/backend/workspace_server/.gradle/file-system.probe
Labels: 🐛 BugFix, 🎮 BE, 상

#243 로고 이미지 public추가
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/public/images/default-user-image.png
  src/frontend/apps/web/public/images/kakao-login-large-narrow.png
  src/frontend/apps/web/public/images/logo-horizontal.png
  src/frontend/apps/web/public/images/logo-icon.png
  src/frontend/apps/web/public/images/logo-vertical.png
  src/frontend/apps/web/src/shared/components/header/header.tsx
Labels: 💄 Design, 🖥️ FE, 중

#244 토큰값 쿠키에서 받아오기
  src/frontend/apps/web/src/shared/services/apis/fetch-instance.api.ts
Labels: ✨ Feature, 🖥️ FE, ♻️ Need To Refactor, 상

#252 파일서버 프로필수정 api passport 적용
  src/backend/file_server/build.gradle
  src/backend/file_server/settings.gradle
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/FileServerApplication.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/controller/FileController.java
Labels: ✨ Feature, 🎮 BE, 상

#261 로그인 로직 적용
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/app/kakao/redirection/page.tsx
  src/frontend/apps/web/public/images/logo-icon.png
  src/frontend/apps/web/src/entities/.keep
  src/frontend/apps/web/src/entities/auth/.keep
  src/frontend/apps/web/src/entities/auth/auth-type.d.ts
  src/frontend/apps/web/src/entities/auth/index.ts
  src/frontend/apps/web/src/entities/index.ts
  src/frontend/apps/web/src/features/auth/api/requestLogin.api.ts
  src/frontend/apps/web/src/features/auth/model/use-login-redirect.ts
  src/frontend/apps/web/src/features/auth/ui/index.ts
  src/frontend/apps/web/src/features/auth/ui/login-button.tsx
  src/frontend/apps/web/src/features/auth/ui/redirect-content.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#254 히스토리서버 채널별 과거 채팅 조회 api(정방향) 구현
  src/backend/history_server/build.gradle
  src/backend/history_server/settings.gradle
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/HistoryServerApplication.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/controller/HistoryController.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/BaseTimeEntity.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/domain/UserChannel.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/ChatMessagePageResponse.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/MessageDto.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/dto/ThreadDto.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/repository/ChatMessageRepository.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/repository/UserChannelRepository.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/service/HistoryQueryService.java
  src/backend/history_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#257 히스토리서버 채널별 과거 채팅 조회 api(역방향) 구현
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/controller/HistoryController.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/repository/ChatMessageRepository.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/service/HistoryQueryService.java
Labels: ✨ Feature, 🎮 BE, 상

#263 파일서버 청크 업로드 요청 포맷 수정 및 small file upload 수정
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/FileServerApplication.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/controller/FileController.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/entity/Files.java
  src/backend/file_server/src/main/java/com/jootalkpia/file_server/service/FileService.java
Labels: ✨ Feature, 🎮 BE, 상

#258 다중 세션 환경에서의 실시간 알림 전달 시스템 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/WebSocketConfig.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompSubscriptionInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/config/interceptor/StompValidationInterceptor.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/PushMessage.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/PushMessageToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/ReadCountMessage.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/state_server/build.gradle
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/ChatMessageToKafka.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/dto/ChannelInfo.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/dto/CommonData.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/dto/PushMessageToKafka.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/entity/common/MessageType.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/entity/common/RedisKeys.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/repository/ChannelRepository.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/service/KafkaConsumer.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/service/KafkaProducer.java
  src/backend/state_server/src/main/java/com/jootalkpia/state_server/service/StateService.java
  src/backend/state_server/src/main/resources/application.yml
Labels: ✨ Feature, 🔧 Build, 🎮 BE, 상

#269 채팅별 과거 채팅조회 (역방향) api 병합실수로 인한 추가 병합
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/controller/HistoryController.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/repository/ChatMessageRepository.java
  src/backend/history_server/src/main/java/com/jootalkpia/history_server/service/HistoryQueryService.java
Labels: 🚀 Deploy, 🎮 BE

#272 프로필 실제 정보 적용 및 로그아웃 버튼 구현
  src/frontend/apps/web/src/entities/auth/index.ts
  src/frontend/apps/web/src/entities/auth/model/auth-type.d.ts
  src/frontend/apps/web/src/entities/index.ts
  src/frontend/apps/web/src/entities/user/.keep
  src/frontend/apps/web/src/entities/user/model/user-store.ts
  src/frontend/apps/web/src/entities/user/model/user-type.d.ts
  src/frontend/apps/web/src/features/auth/api/requestLogin.api.ts
  src/frontend/apps/web/src/features/auth/model/use-login-redirect.ts
  src/frontend/apps/web/src/features/auth/model/use-logout.ts
  src/frontend/apps/web/src/features/auth/ui/logout-button.tsx
  src/frontend/apps/web/src/features/user/ui/profile-nickname.tsx
  src/frontend/apps/web/src/features/user/ui/profile-picture.tsx
  src/frontend/apps/web/src/features/user/ui/profile-popover.tsx
Labels: ✨ Feature, 🖥️ FE, ♻️ Need To Refactor, 상

#278 auth서버 회원가입시 기본 이미지 변경
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
  src/backend/auth_server/src/main/resources/application.yml
Labels: 🐛 BugFix, 🎮 BE, 상

#280 채팅 내역 무한 스크롤 기능 추가
  src/frontend/apps/web/next.config.mjs
  src/frontend/apps/web/src/features/chat/api/get-history-chat.api.ts
  src/frontend/apps/web/src/features/chat/api/index.ts
  src/frontend/apps/web/src/features/chat/lib/index.ts
  src/frontend/apps/web/src/features/chat/lib/process-chat-history.util.ts
  src/frontend/apps/web/src/features/chat/model/chat-data.type.ts
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/model/use-forward-infinite-history.ts
  src/frontend/apps/web/src/features/chat/model/use-reverse-infinite-history.ts
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-history-dummy.ts
  src/frontend/apps/web/src/features/chat/ui/chat-history-forward.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-history-item.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-history-reverse.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-message-item.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-message-list.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/apps/web/src/shared/providers/stomp-websocket-provider.tsx
  src/frontend/apps/web/src/shared/services/apis/client-fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch-instance.api.ts
  src/frontend/apps/web/src/shared/services/apis/index.ts
  src/frontend/apps/web/src/shared/services/apis/ismorphic-fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/querykey.ts
  src/frontend/apps/web/src/shared/services/apis/server-fetch.api.ts
  src/frontend/apps/web/src/shared/services/lib/utils.ts
Labels: ✨ Feature, 🖥️ FE, ♻️ Need To Refactor, 상

#283 huddle 이름 변경 및 멀티 스레드 속성 변경
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/push_server/src/main/resources/application.yml
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/KafkaProducer.java
Labels: 🔧 Build, 🎮 BE, 중

#270 시그널링 서버 설계 수정
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/SignalingServerApplication.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/config/RedisConfig.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/config/WebRtcConfig.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/config/WebSocketConfig.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/model/Huddle.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/model/KurentoUserSession.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/ChannelHuddleRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/HuddleCacheRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/HuddleParticipantsRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/HuddlePipelineRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/repository/UserHuddleRepository.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/CallHandler.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/Huddle.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/HuddleManager.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/KurentoHandler.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/UserRegistry.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/UserSession.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/ValidationUtils.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/HuddleService.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/KurentoService.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/util/ValidationUtils.java
Labels: ✨ Feature, 🎮 BE, 상

#286 시그널링서버 허들 여부 표현 api 구현 및 허들-카프카 설정
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/model/MessageToKafka.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/CallHandler.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/HuddleManager.java
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/service/KafkaProducer.java
Labels: ✨ Feature, 🎮 BE, 상

#288 HOTFIX! Auth Token및 userId 값 변경
  src/frontend/apps/web/app/stock/layout.tsx
  src/frontend/apps/web/src/features/auth/api/requestLogin.api.ts
  src/frontend/apps/web/src/features/chat/api/get-history-chat.api.ts
  src/frontend/apps/web/src/features/chat/api/get-ping.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-file.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-smallfile.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-thumbnail.api.ts
  src/frontend/apps/web/src/features/chat/lib/format-chat-time.util.ts
  src/frontend/apps/web/src/features/chat/model/use-messages.ts
  src/frontend/apps/web/src/features/chat/ui/chat-history-forward.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-textarea.tsx
  src/frontend/apps/web/src/shared/providers/stomp-websocket-provider.tsx
  src/frontend/apps/web/src/shared/services/apis/client-fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch-instance.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch-method.api.ts
  src/frontend/apps/web/src/shared/services/apis/fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/index.ts
  src/frontend/apps/web/src/shared/services/apis/server-fetch.api.ts
  src/frontend/apps/web/src/shared/services/lib/get-accesstoken-from-cookie.util.ts
  src/frontend/apps/web/src/shared/services/lib/get-userid-from-cookie.util.ts
  src/frontend/apps/web/src/shared/services/lib/index.ts
  src/frontend/apps/web/src/shared/services/lib/utils.ts
Labels: 🐛 BugFix, 🚑 !HOTFIX, 🖥️ FE, 상

#285 채팅서버 비디오 응답 반환시 썸네일 아이디 반환 로직 삭제
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/messgaeDto/VideoResponse.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/jpa/FileRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
Labels: 🐛 BugFix, 🎮 BE, 상

#294 워크스페이스 서버 채널 리스트 조회시 안읽은 메세지 수 추가
  src/backend/workspace_server/.gradle/8.11.1/checksums/checksums.lock
  src/backend/workspace_server/.gradle/8.11.1/checksums/md5-checksums.bin
  src/backend/workspace_server/.gradle/8.11.1/checksums/sha1-checksums.bin
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.bin
  src/backend/workspace_server/.gradle/8.11.1/executionHistory/executionHistory.lock
  src/backend/workspace_server/.gradle/8.11.1/fileChanges/last-build.bin
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.bin
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/fileHashes.lock
  src/backend/workspace_server/.gradle/8.11.1/fileHashes/resourceHashesCache.bin
  src/backend/workspace_server/.gradle/8.11.1/gc.properties
  src/backend/workspace_server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/backend/workspace_server/.gradle/buildOutputCleanup/cache.properties
  src/backend/workspace_server/.gradle/buildOutputCleanup/outputFiles.bin
  src/backend/workspace_server/.gradle/file-system.probe
  src/backend/workspace_server/.gradle/vcs-1/gc.properties
  src/backend/workspace_server/build.gradle
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/dto/SimpleChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/ChatMessage.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Message.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/UserChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
  src/backend/workspace_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#291 MinutePriceSimpleResponse 변수 이름 변경
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/MinutePriceResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceSimpleResponse.java
Labels: 🎮 BE, 하

#296 시그널링서버 최종 설정
  src/backend/signaling_server/src/main/java/com/jootalkpia/signaling_server/rtc/UserSession.java
Labels: ✨ Feature, 🎮 BE, 상

#298 워크스페이스 채널 생성시 socket 로직 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/WorkspaceToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/controller/WorkSpaceController.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/dto/WorkspaceToKafka.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/KafkaProducer.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
Labels: ✨ Feature, 🎮 BE, 상

#299 허들 생성시 웹소켓을 통한 알림 구현 - consume
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/dto/HuddleToKafka.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/KafkaConsumer.java
  src/backend/chat_server/src/main/resources/application.yml
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/KafkaProducer.java
Labels: ✨ Feature, 🎮 BE, 상

#289 사용자 닉네임 변경
  src/frontend/apps/web/src/features/auth/api/requestLogin.api.ts
  src/frontend/apps/web/src/features/user/api/change-nickname.api.ts
  src/frontend/apps/web/src/features/user/model/profile-change-reducer.ts
  src/frontend/apps/web/src/features/user/ui/profile-nickname.tsx
  src/frontend/apps/web/src/shared/services/lib/cookie.ts
  src/frontend/apps/web/src/shared/services/lib/index.ts
  src/frontend/packages/ui/src/components/Input/input.stories.tsx
  src/frontend/packages/ui/src/components/Input/input.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 상

#302 워크스페이스서버 passport 적용
  src/backend/workspace_server/build.gradle
  src/backend/workspace_server/settings.gradle
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/WorkspaceServerApplication.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/config/WebConfig.JAVA
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/controller/WorkSpaceController.java
Labels: ✨ Feature, 🎮 BE, 상

#304 주식 실시간 리스트 Open api연결
  src/frontend/apps/web/app/stock/layout.tsx
  src/frontend/apps/web/src/features/stock/api/get-access-token.ts
  src/frontend/apps/web/src/features/stock/index.tsx
  src/frontend/apps/web/src/features/stock/lib/index.ts
  src/frontend/apps/web/src/features/stock/lib/stock-chart.util.ts
  src/frontend/apps/web/src/features/stock/lib/stock-realtime.util.ts
  src/frontend/apps/web/src/features/stock/model/index.ts
  src/frontend/apps/web/src/features/stock/model/stock.mock.ts
  src/frontend/apps/web/src/features/stock/model/stock.types.ts
  src/frontend/apps/web/src/features/stock/model/stocks-table.columns.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-info.tsx
  src/frontend/apps/web/src/features/stock/ui/stocks-list-table.tsx
  src/frontend/apps/web/src/shared/providers/index.ts
  src/frontend/apps/web/src/shared/providers/websocket-provider.tsx
Labels: ✨ Feature, 🖥️ FE, ♻️ Need To Refactor

#311 워크스페이스 구현하기
  src/frontend/apps/web/app/api/auth/token/route.ts
  src/frontend/apps/web/app/stock/[stockSlug]/page.tsx
  src/frontend/apps/web/package.json
  src/frontend/apps/web/src/features/.gitkeep
  src/frontend/apps/web/src/features/auth/model/use-logout.ts
  src/frontend/apps/web/src/features/chat/api/get-history-chat.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-chunk-retry-api.ts
  src/frontend/apps/web/src/features/chat/api/upload-file.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-smallfile.api.ts
  src/frontend/apps/web/src/features/chat/api/upload-thumbnail.api.ts
  src/frontend/apps/web/src/features/chat/lib/validate-filesize.util.ts
  src/frontend/apps/web/src/features/chat/model/index.ts
  src/frontend/apps/web/src/features/chat/model/send-message.ts
  src/frontend/apps/web/src/features/chat/model/use-chat-messages.ts
  src/frontend/apps/web/src/features/chat/model/use-chat-subscribe.ts
  src/frontend/apps/web/src/features/chat/model/use-forward-infinite-history.ts
  src/frontend/apps/web/src/features/chat/model/use-reverse-infinite-history.ts
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-history-forward.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-history-reverse.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-message-list.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-textarea.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/apps/web/src/features/chat/ui/file-modal.tsx
  src/frontend/apps/web/src/features/workspace/api/create-channel.api.ts
  src/frontend/apps/web/src/features/workspace/api/get-workspace-list.api.ts
  src/frontend/apps/web/src/features/workspace/api/get-workspace-page-props.ts
  src/frontend/apps/web/src/features/workspace/api/index.ts
  src/frontend/apps/web/src/features/workspace/lib/get-workspace-id.ts
  src/frontend/apps/web/src/features/workspace/lib/index.ts
  src/frontend/apps/web/src/features/workspace/model/index.ts
  src/frontend/apps/web/src/features/workspace/model/subscription.type.ts
  src/frontend/apps/web/src/features/workspace/model/use-workspace-channels.tsx
  src/frontend/apps/web/src/features/workspace/model/use-workspace-messages.ts
  src/frontend/apps/web/src/features/workspace/model/use-workspace-subscription.ts
  src/frontend/apps/web/src/features/workspace/model/workspace-form-schema.ts
  src/frontend/apps/web/src/features/workspace/model/workspace-id.ts
  src/frontend/apps/web/src/features/workspace/ui/sidebar-container.tsx
  src/frontend/apps/web/src/features/workspace/ui/workspace-modal.tsx
  src/frontend/apps/web/src/shared/hooks/.keep
  src/frontend/apps/web/src/shared/index.ts
  src/frontend/apps/web/src/shared/providers/chat-id-provider.tsx
  src/frontend/apps/web/src/shared/providers/index.ts
  src/frontend/apps/web/src/shared/services/apis/client-fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/index.ts
  src/frontend/apps/web/src/shared/services/apis/querykey.ts
  src/frontend/apps/web/src/shared/services/apis/server-fetch.api.ts
  src/frontend/apps/web/src/shared/services/apis/tagkey.ts
  src/frontend/apps/web/src/shared/services/index.ts
  src/frontend/package.json
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Form/form.stories.tsx
  src/frontend/packages/ui/src/components/Form/form.tsx
  src/frontend/packages/ui/src/components/Form/index.ts
  src/frontend/packages/ui/src/components/Modal/index.ts
  src/frontend/packages/ui/src/components/Modal/modal.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 🖥️ FE, 상

#310 알림 구독 구현
  src/frontend/apps/web/app/stock/layout.tsx
  src/frontend/apps/web/src/features/alarm/index.ts
  src/frontend/apps/web/src/features/alarm/model/toast-alarm.tsx
  src/frontend/apps/web/src/shared/providers/stomp-websocket-provider.tsx
Labels: ✨ Feature, 🖥️ FE, ♻️ Need To Refactor, 상

#303 채팅서버 rdb선행작업 삭제 후 snowflake 구현
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/controller/ChatController.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/ReplyThread.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/domain/Thread.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/repository/jpa/ThreadRepository.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/service/ChatService.java
  src/backend/chat_server/src/main/java/com/jootalkpia/chat_server/util/SnowflakeIdGenerator.java
Labels: ✨ Feature, 🎮 BE

#317 읽지 않은 메시지 알림 구현
  src/frontend/apps/web/src/features/chat/ui/chat-history-reverse.tsx
  src/frontend/apps/web/src/features/chat/ui/file-preview-item.tsx
  src/frontend/apps/web/src/features/stock/api/get-access-token.ts
  src/frontend/apps/web/src/features/stock/ui/stock-info.tsx
  src/frontend/apps/web/src/features/workspace/api/index.ts
  src/frontend/apps/web/src/features/workspace/api/join-channel.api.ts
  src/frontend/apps/web/src/features/workspace/model/index.ts
  src/frontend/apps/web/src/features/workspace/model/subscription.type.ts
  src/frontend/apps/web/src/features/workspace/model/use-unread-messages.ts
  src/frontend/apps/web/src/features/workspace/model/use-unread-subscription.ts
  src/frontend/apps/web/src/features/workspace/model/use-workspace-channels.tsx
  src/frontend/apps/web/src/features/workspace/ui/sidebar-container.tsx
  src/frontend/apps/web/src/features/workspace/ui/workspace-modal.tsx
  src/frontend/apps/web/src/shared/services/apis/querykey.ts
  src/frontend/apps/web/src/shared/services/apis/tagkey.ts
Labels: ✨ Feature, 🖥️ FE, 상
