Repository sgdevcamp2025/c_sharp, pull requests merged in 2025-01, with the labels that each got.

#2 Issue, Bug & PR Template 설정
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 Docs, 📦 Environment, 🖥️ FE, 🎮 BE

#35 주식 서버 초기 설정, 당일 일분봉 API 연결 및 데이터 가공
  src/backend/stock_server/.gitattributes
  src/backend/stock_server/.gitignore
  src/backend/stock_server/build.gradle
  src/backend/stock_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/stock_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/stock_server/gradlew
  src/backend/stock_server/gradlew.bat
  src/backend/stock_server/settings.gradle
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/StockServerApplication.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/MinutePriceCaller.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/controller/MinutePriceController.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/MinutePriceDto.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/MinutePriceService.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/FeignConfig.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/property/BaseProperties.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/property/MinutePriceProperties.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/property/TokenProperties.java
  src/backend/stock_server/src/main/resources/application.yml
  src/backend/stock_server/src/test/java/com/jootalkpia/stock_server/StockServerApplicationTests.java
Labels: ✨ Feature, 📦 Environment, 🎮 BE, ♻️ Need To Refactor, 상

#22 버튼 컴포넌트 추가 및 스토리북 작성
  src/frontend/package.json
  src/frontend/packages/ui/src/components/Button/button.stories.tsx
  src/frontend/packages/ui/src/components/Button/button.tsx
  src/frontend/packages/ui/tailwind.config.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#23 Textarea 구현하기
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.stories.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/index.ts
  src/frontend/packages/ui/src/components/Textarea/index.ts
  src/frontend/packages/ui/src/components/Textarea/textarea.stories.tsx
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/packages/ui/src/components/index.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#36 react-toast 구현하기
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Toast/index.ts
  src/frontend/packages/ui/src/components/Toast/toast.stories.tsx
  src/frontend/packages/ui/src/components/Toast/toast.tsx
  src/frontend/packages/ui/src/components/Toast/toaster.tsx
  src/frontend/packages/ui/src/hooks/.gitkeep
  src/frontend/packages/ui/src/hooks/Toast/index.ts
  src/frontend/packages/ui/src/hooks/Toast/use-toast.ts
  src/frontend/packages/ui/src/hooks/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#24 Resizable
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Resizable/index.ts
  src/frontend/packages/ui/src/components/Resizable/resizable.stories.tsx
  src/frontend/packages/ui/src/components/Resizable/resizable.tsx
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#30 배지 기능 구현
  src/frontend/packages/ui/src/components/Badge/badge.stories.tsx
  src/frontend/packages/ui/src/components/Badge/badge.tsx
  src/frontend/packages/ui/src/components/Badge/index.ts
  src/frontend/packages/ui/src/components/index.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#38 패키지 누락 수정
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.tsx
  src/frontend/pnpm-lock.yaml
Labels: 🐛 BugFix, 🚑 !HOTFIX, 🖥️ FE, 상

#40 아바타 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Avatar/avatar.stories.tsx
  src/frontend/packages/ui/src/components/Avatar/avatar.tsx
  src/frontend/packages/ui/src/components/Avatar/index.ts
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#51 프론트엔드 통합 CI 파일 설정
  .github/workflows/fe-ci.yml
  src/frontend/.eslintignore
  src/frontend/.eslintrc.js
  src/frontend/.gitignore
  src/frontend/.prettierignore
  src/frontend/.prettierrc
  src/frontend/README.md
  src/frontend/apps/web/app/layout.tsx
  src/frontend/apps/web/src/shared/components/react-query/RQProvider.tsx
  src/frontend/apps/web/tailwind.config.ts
  src/frontend/dangerfile.ts
  src/frontend/package.json
  src/frontend/packages/eslint-config/next.js
  src/frontend/packages/eslint-config/package.json
  src/frontend/packages/typescript-config/base.json
  src/frontend/packages/ui/.storybook/main.ts
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Avatar/avatar.tsx
  src/frontend/packages/ui/src/components/Badge/badge.tsx
  src/frontend/packages/ui/src/components/Button/button.stories.tsx
  src/frontend/packages/ui/src/components/Button/button.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.stories.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.tsx
  src/frontend/packages/ui/src/components/Resizable/index.ts
  src/frontend/packages/ui/src/components/Resizable/resizable.stories.tsx
  src/frontend/packages/ui/src/components/Resizable/resizable.tsx
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/packages/ui/src/components/Toast/index.ts
  src/frontend/packages/ui/src/components/Toast/toast.tsx
  src/frontend/packages/ui/src/components/Toast/toaster.tsx
  src/frontend/packages/ui/src/hooks/Toast/use-toast.ts
  src/frontend/packages/ui/tailwind.config.ts
  src/frontend/pnpm-lock.yaml
  src/frontend/tsconfig.json
Labels: 🚀 Deploy, ✨ Feature, 📦 Environment, 🖥️ FE, 상

#47 passport 관련 공통 모듈 구현
  src/backend/common_module/.gitattributes
  src/backend/common_module/.gitignore
  src/backend/common_module/build.gradle
  src/backend/common_module/gradle/wrapper/gradle-wrapper.jar
  src/backend/common_module/gradle/wrapper/gradle-wrapper.properties
  src/backend/common_module/gradlew
  src/backend/common_module/gradlew.bat
  src/backend/common_module/settings.gradle
  src/backend/common_module/src/main/java/com/jootalkpia/CommonModuleApplication.java
  src/backend/common_module/src/main/java/com/jootalkpia/aop/JootalkpiaAuthenticationContext.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/HMACEncoder.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportExtractor.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportGenerator.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/PassportValidator.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/component/Passport.java
  src/backend/common_module/src/main/java/com/jootalkpia/passport/component/UserInfo.java
  src/backend/common_module/src/main/resources/application.yml
Labels: ✨ Feature, 📦 Environment, 🎮 BE, 상

#46 separator 구현 및 스토리북 문서화
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Resizable/resizable.stories.tsx
  src/frontend/packages/ui/src/components/Separate/index.ts
  src/frontend/packages/ui/src/components/Separate/separator.tsx
  src/frontend/packages/ui/src/components/Separate/seperator.stories.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#53 인증서버 초기셋팅
  src/backend/auth_server/.gitattributes
  src/backend/auth_server/.gitignore
  src/backend/auth_server/build.gradle
  src/backend/auth_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/auth_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/auth_server/gradlew
  src/backend/auth_server/gradlew.bat
  src/backend/auth_server/settings.gradle
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/AuthServerApplication.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/config/RedisConfig.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/config/SecurityConfig.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/exception/CustomException.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/exception/GlobalExceptionHandler.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/exception/ResponseStatusSetterAdvice.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtAuthenticationFilter.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtTokenProvider.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/JwtValidationType.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/redis/Token.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/response/ApiResponseDto.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/response/ErrorCode.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/security/CustomAccessDeniedHandler.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/security/CustomJwtAuthenticationEntryPoint.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/security/UserAuthentication.java
  src/backend/auth_server/src/main/resources/application.yml
  src/backend/auth_server/src/test/java/com/jootalkpia/auth_server/AuthServerApplicationTests.java
Labels: ✨ Feature, 📦 Environment, 🎮 BE, 상

#55 pipeline 제거
  .github/workflows/fe-ci.yml
  src/frontend/.gitignore
  src/frontend/package.json
  src/frontend/packages/ui/.eslintignore
  src/frontend/pnpm-lock.yaml
  src/frontend/turbo.json
Labels: 📦 Environment, 🖥️ FE, 상

#50 토큰 발급, 당일일분봉 API 요청 스케줄링
  src/backend/stock_server/.gitignore
  src/backend/stock_server/dev.env
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/StockServerApplication.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/MinutePriceCaller.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/StockCaller.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/controller/MinutePriceController.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/controller/StockController.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/domain/Schedule.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/domain/StockCode.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/MinutePriceDto.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/request/TokenRequestBody.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceSimpleResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/TokenResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/MinutePriceService.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/StockService.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/FeignConfig.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/TaskSchedulerConfiguration.java
  src/backend/stock_server/src/main/resources/application.yml
Labels: ✨ Feature, 🔧 Build, 🎮 BE, ♻️ Need To Refactor, 상

#48 워크스페이스 채널 목록 조회 API
  .DS_Store
  .github/.DS_Store
  .github/workflows/ci.yml
  src/.idea/.gitignore
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/src.iml
  src/.idea/vcs.xml
  src/backend/chat-service/Dockerfile
  src/backend/workspace_server/.gitattributes
  src/backend/workspace_server/.gitignore
  src/backend/workspace_server/Dockerfile
  src/backend/workspace_server/build.gradle
  src/backend/workspace_server/docker-compose.yml
  src/backend/workspace_server/gradle/wrapper/gradle-wrapper.jar
  src/backend/workspace_server/gradle/wrapper/gradle-wrapper.properties
  src/backend/workspace_server/gradlew
  src/backend/workspace_server/gradlew.bat
  src/backend/workspace_server/local.env
  src/backend/workspace_server/settings.gradle
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/WorkspaceServerApplication.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/controller/WorkSpaceController.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/dto/ChannelListDTO.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/dto/SimpleChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Channels.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Mention.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/UserChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Users.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/WorkSpace.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/CustomException.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/ErrorCode.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/repository/ChannelRepository.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/repository/UserChannelRepository.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/repository/WorkSpaceRepository.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/util/ValidationUtils.java
  src/backend/workspace_server/src/main/resources/application.yml
  src/backend/workspace_server/src/test/java/com/jootalkpia/workspace_server/WorkspaceServerApplicationTests.java
  src/infra/docker-compose.yml
Labels: ✨ Feature, 🎮 BE, 상

#44 테이블 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/DataTable/data-table.stories.tsx
  src/frontend/packages/ui/src/components/DataTable/data-table.tsx
  src/frontend/packages/ui/src/components/DataTable/index.ts
  src/frontend/packages/ui/src/components/Table/index.ts
  src/frontend/packages/ui/src/components/Table/table.stories.tsx
  src/frontend/packages/ui/src/components/Table/table.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#56 워크스페이스 채널생성 API 구현
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/controller/WorkSpaceController.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/dto/SimpleChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/BaseEntity.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Channels.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Mention.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/UserChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/Users.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/WorkSpace.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/CustomException.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/ErrorCode.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/ErrorResponse.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/GlobalExceptionHandler.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/repository/UserChannelRepository.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
Labels: ✨ Feature, 🎮 BE, 상

#57 #33 feat(be): 채널가입 api 구현
  src/backend/.idea/.gitignore
  src/backend/.idea/backend.iml
  src/backend/.idea/compiler.xml
  src/backend/.idea/dataSources.xml
  src/backend/.idea/gradle.xml
  src/backend/.idea/misc.xml
  src/backend/.idea/modules.xml
  src/backend/.idea/vcs.xml
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/controller/WorkSpaceController.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/entity/UserChannel.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/exception/common/ErrorCode.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/repository/UserRepository.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/service/WorkSpaceService.java
  src/backend/workspace_server/src/main/java/com/jootalkpia/workspace_server/util/ValidationUtils.java
Labels: ✨ Feature, 🎮 BE, 상

#72 유저프로필 popover 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Input/index.ts
  src/frontend/packages/ui/src/components/Input/input.stories.tsx
  src/frontend/packages/ui/src/components/Input/input.tsx
  src/frontend/packages/ui/src/components/Label/index.ts
  src/frontend/packages/ui/src/components/Label/label.stories.ts
  src/frontend/packages/ui/src/components/Label/label.tsx
  src/frontend/packages/ui/src/components/Popover/index.ts
  src/frontend/packages/ui/src/components/Popover/popover.stories.tsx
  src/frontend/packages/ui/src/components/Popover/popover.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#73 허들 툴바 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Toggle/index.ts
  src/frontend/packages/ui/src/components/Toggle/toggle-group.stories.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle-group.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle.stories.tsx
  src/frontend/packages/ui/src/components/Toggle/toggle.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#79 주식 상세 페이지 레이아웃 구성하기
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/app/layout.tsx
  src/frontend/apps/web/app/not-found.tsx
  src/frontend/apps/web/src/features/chat/.keep
  src/frontend/apps/web/src/features/chat/chat-container.tsx
  src/frontend/apps/web/src/features/chat/index.tsx
  src/frontend/apps/web/src/features/stock/.keep
  src/frontend/apps/web/src/features/stock/index.tsx
  src/frontend/apps/web/src/features/stock/stock-layout.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#87 주식 서버 1분봉 데이터 저장 및 캔들 차트 과거 데이터 조회 API 구현
  src/backend/stock_server/.gitignore
  src/backend/stock_server/build.gradle
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/advice/StockCaller.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/controller/StockController.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/domain/Schedule.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/domain/StockCode.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/MinutePrice.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/CandlePriceHistoryResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceDetailedResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/dto/response/MinutePriceSimpleResponse.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/repository/MinutePriceRepository.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/stocks/service/StockService.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/FeignConfig.java
  src/backend/stock_server/src/main/java/com/jootalkpia/stock_server/support/config/MongoConfig.java
  src/backend/stock_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#89 사이드바 구현
  src/frontend/packages/ui/package.json
  src/frontend/packages/ui/src/components/Collapsible/collapsible.stories.tsx
  src/frontend/packages/ui/src/components/Collapsible/collapsible.tsx
  src/frontend/packages/ui/src/components/Collapsible/index.ts
  src/frontend/packages/ui/src/components/Sheet/index.ts
  src/frontend/packages/ui/src/components/Sheet/sheet.stories.tsx
  src/frontend/packages/ui/src/components/Sheet/sheet.tsx
  src/frontend/packages/ui/src/components/Sidebar/index.ts
  src/frontend/packages/ui/src/components/Sidebar/sidebar.stories.tsx
  src/frontend/packages/ui/src/components/Sidebar/sidebar.tsx
  src/frontend/packages/ui/src/components/Skeleton/index.ts
  src/frontend/packages/ui/src/components/Skeleton/skeleton.stories.tsx
  src/frontend/packages/ui/src/components/Skeleton/skeleton.tsx
  src/frontend/packages/ui/src/components/Tooltip/index.ts
  src/frontend/packages/ui/src/components/Tooltip/tooltip.stories.tsx
  src/frontend/packages/ui/src/components/Tooltip/tooltip.tsx
  src/frontend/packages/ui/src/components/index.ts
  src/frontend/packages/ui/src/hooks/Sidebar/index.ts
  src/frontend/packages/ui/src/hooks/Sidebar/use-mobile.tsx
  src/frontend/packages/ui/src/hooks/index.ts
  src/frontend/packages/ui/src/styles/globals.css
  src/frontend/packages/ui/tailwind.config.ts
  src/frontend/pnpm-lock.yaml
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#88 Chatting 레이아웃 구성하기
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/src/features/chat/chat-container.tsx
  src/frontend/apps/web/src/features/chat/index.tsx
  src/frontend/apps/web/src/features/chat/ui/avatarlist.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-container.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-content.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-header.tsx
  src/frontend/apps/web/src/features/chat/ui/chat-section.tsx
  src/frontend/apps/web/src/features/chat/ui/content-avatar.tsx
  src/frontend/apps/web/src/features/chat/ui/content-text.tsx
  src/frontend/packages/ui/src/components/Avatar/avatar.stories.tsx
  src/frontend/packages/ui/src/components/Avatar/avatar.tsx
  src/frontend/packages/ui/src/components/ChatTextarea/chat-textarea.tsx
  src/frontend/packages/ui/src/components/Textarea/textarea.tsx
  src/frontend/packages/ui/tailwind.config.ts
Labels: ✨ Feature, 💄 Design, 🖥️ FE, 상

#86 인증서버 내 kakao social login을 통한 회원가입
  src/backend/auth_server/build.gradle
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/AuthServerApplication.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/dto/UserInfoResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/dto/UserLoginRequest.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/KakaoApiClient.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/KakaoAuthApiClient.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/KakaoSocialService.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/response/KakaoAccessTokenResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/response/KakaoAccount.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/response/KakaoUserProfile.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/kakao/response/KakaoUserResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/client/service/SocialService.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/config/SecurityConfig.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/TokenRepository.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/jwt/TokenService.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/response/ErrorCode.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserController.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/controller/UserControllerDocs.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/BaseTimeEntity.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/SocialType.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/domain/User.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/LoginSuccessResponse.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/dto/TokenDto.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/repository/UserRepository.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/repository/UserRepositoryCustom.java
  src/backend/auth_server/src/main/java/com/jootalkpia/auth_server/user/service/UserService.java
  src/backend/auth_server/src/main/resources/application.yml
Labels: ✨ Feature, 🎮 BE, 상

#93 메인페이지(주식리스트 테이블) 레이아웃 구현
  src/frontend/apps/web/app/(main)/[stockSlug]/page.tsx
  src/frontend/apps/web/app/(main)/layout.tsx
  src/frontend/apps/web/app/(main)/page.tsx
  src/frontend/apps/web/src/features/stock/index.tsx
  src/frontend/apps/web/src/features/stock/stock-layout.tsx
  src/frontend/apps/web/src/features/stock/ui/stock-detail-layout.tsx
  src/frontend/apps/web/src/features/stock/ui/stocks-list.tsx
  src/frontend/apps/web/src/shared/components/header/header.tsx
  src/frontend/packages/ui/src/components/DataTable/data-table.tsx
Labels: ✨ Feature, 💄 Design, 🖥️ FE, ♻️ Need To Refactor, 상
